### ISSUE TITLE
Passing the chrome secure origin error

### ISSUE THREAD

**Issue by oreporan** [vibornoff/webcrypto-shim#6]
Chrome added this security restriction which causes the native Crypto to fail over non-SSL (or localhost) request.
As seen [here](http://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features)

Since your library does nothing in chrome (since it supports the native library) my question is:

1. If I edit your code to also use shim in chrome, will it work over chrome over an http request (non-secure).

2. if (1) is true, can you add some setting for this?

thanks

**Comment by vibornoff** [comment]
My library is nothing more then a thin shim around the native crypto. Also, as you mention, it does nothing in chrome since its native crypto just works. So short answer is No, it won't work over an insecure channel. 

BTW, localhost is considered secure for http requests. It works for me till now.

Note that crypto stuff over an insecure channel is very bad practice in general. Your system becomes vulnerable to MiTM attacks.
